// State de productos
export const OBTENER_PRODUCTOS_EXITO = 'OBTENER_PRODUCTOS_EXITO';
export const FILTRAR_MOVIMIENTOS = 'FILTRAR_MOVIMIENTOS';
export const OBTENER_PUNTOS_GANADOS = 'OBTENER_PUNTOS_GANADOS';
